server:
  port: 8080
  servlet:
    context-path: /admin

admin:
  fileUploadPath: /Users/gutongwei/Documents/Development/jianlang/upload

spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/

  mvc:
    static-path-pattern: /static/**
  datasource:
    url : jdbc:mysql://39.108.88.223:12306/gzgh_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username : admin
    password : gobest_123$%^&
mybatis-plus:
  mapper-locations: classpath*:com/example/db/mapping/*.xml
  typeAliasesPackage: com.example.db.pojo
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    key-generator: com.baomidou.mybatisplus.incrementer.PostgreKeyGenerator
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

